; ZX Spectrum UDG Sprite Data
; Generated by ZX Spectrum UDG Editor
;
; Sprite dimensions: 1x1 characters (8x8 pixels)
; Total characters: 1
; UDG data size: 8 bytes
; Attribute data size: 1 bytes

; -----------------------------------------------------------------------------
; Constants
; -----------------------------------------------------------------------------
SPRITE_WIDTH    equ 1          ; Width in characters
SPRITE_HEIGHT   equ 1          ; Height in characters
SPRITE_CHARS    equ 1         ; Total characters
UDG_BYTES       equ 8        ; Bytes of UDG pixel data
FIRST_UDG_CHAR  equ 144         ; First UDG character code

; -----------------------------------------------------------------------------
; UDG Pixel Data (8 bytes per character, MSB=leftmost pixel)
; -----------------------------------------------------------------------------
sprite_udg_data:
        defb $30,$78,$33,$7E,$B0,$38,$68,$4C  ; char 0 (row 0, col 0)

; -----------------------------------------------------------------------------
; Attribute Data (1 byte per character)
; Format: FBPPPIII where F=flash, B=bright, P=paper(0-7), I=ink(0-7)
; -----------------------------------------------------------------------------
sprite_attr_data:
        defb $47  ; row 0